name: "Release"

on:
  pull_request:
    types:
      - closed
    branches:
      - latest
      
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        if: github.event.pull_request.merged
        id: tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: latest
          release_strategy: none
          tag_format: "v%major%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
