name: "Tag"

on:
  pull_request:
    types:
      - closed
      
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        id: tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}