name: Release Tag

on:
  pull_request:
    types:
      - closed
    branches:
      - master


jobs:
  tag:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        env:
          semantic-version: patch
        with:
          bump_version_scheme: ${{ env.semantic-version }}
          tag_prefix: v