name: Keep the versions up-to-date

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Version Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false